### PR TITLE
Answering BasicsAndArrays Questions

### PR DESCRIPTION
**Pull request by paramkpr**

### CODE REVIEW

**Comment by ViRu-ThE-ViRuS** [comment]
i will merge when all 3 questions are solved ;)

**Comment by paramkpr** [comment]
But like I can literally just merge it myself :p

**Comment by ViRu-ThE-ViRuS** [comment]
Done mess with me boy!!!

**Comment by paramkpr** [comment]
The WIP bot is _awesome_. Nice.

**Comment by ViRu-ThE-ViRuS** [comment]
@paramkpr nice job! Merging.

**Pull request merged**
