### PR TITLE
SolutionSet_Python_Naman

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by paramkpr** [comment]
Add the rest of the solutions and then I will merge.

**Comment by IronicalCoder** [comment]
Add all final solutions for the QuestionSet in BasicsandArrays

**Comment by ViRu-ThE-ViRuS** [comment]
almost done.. there seems to be some error in the solution 2 file... looks like you have just pasted from idle, this is not valid code.... i want it without the `>>>`. Nice job working on this!
Dont forget to squash all commits if you can in the end.

**Comment by ViRu-ThE-ViRuS** [comment]
Merging

**Comment by paramkpr** [comment]
@IronicalCoder Good job on your first merge

**Pull request merged**
